### ISSUE TITLE
Variáveis CSS

### ISSUE THREAD

**Issue by liammaricato** [matheuscubas/the_odin_project#1]
Uma coisa que você pode adicionar, tanto para organizar seu código quanto pra manter ele sempre consistente, é usar variáveis CSS. Isso serve pra você gravar alguns valores que serão **recorrentes** no seu css, assim você pode facilmente usar as mesmas cores ou margens, sem precisar ficar lembrando ou copiando de outras partes do código.

Um bom exemplo seria essa cor `#c6c9cd`, você usa ela em 3 pedaços diferentes no código. Você pode incluir esse trecho no início do seu arquivo de CSS:
```
:root {
    --color-1: #c6c9cd;
}
```

Isso adicionará a variável `--color-1` à sua raiz, assim você pode chamá-la globalmente no arquivo e ela estará disponível, por exemplo:
```
h1 {
    color: var(--color-1);
}
```

Você pode adicionar outros valores pra usar também, assim você não se perde e mantém seus valores consistentes. Uma margem por exemplo
```
:root {
    --margin-s: 10px;
    --margin-m: 20px;
    --margin-l: 40px;
    --margin-xl: 60px;
}

h1 {
    margin-top: var(--margin-xl);
    margin-left: var(--margin-s);
}

h2 {
    margin: var(--margin-m) var(--margin-l) var(--margin-xl) var(--margin-s);
}
```

No final das contas, pode não ser a sintaxe mais bonita kkkkkk mas assim que você precisar mudar suas cores e tiver que alterar **cada um** dos lugares que você usou aquela cor, acho que vai desejar ter usado as variáveis DHSJHDKAJS espero que tenha sido útil

**Comment by matheuscubas** [comment]
Realmente, faz muito sentido fazer desta forma obrigado pela dica Liam
