### ISSUE TITLE
Diminuir escopo de estilização

### ISSUE THREAD

**Issue by DavideCarvalho** [matheuscubas/the_odin_project#2]
Estilizar as suas classes de forma concatenada é legal, assim você mantém o escopo da estilização dentro dessas lógicas, e você sabe onde que ta as coisas no html depois, e.g:

Trocar de:

```css
.footer-container {
  /*...*/
}

.footer-menu {
  /*...*/
}
```

para:

```css
.footer-container {
  /*...*/
}

.footer-container .footer-menu {
  /*...*/
}
```

**Comment by matheuscubas** [comment]
Realmente, isso deve facilitar quando eu for reler algum projeto antigo e não lembrar mais o que eu estava fazendo, obrigado Davi, vou implementar isso no futuro
